/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as IndustriasRouteImport } from './routes/industrias'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ActivarIaRouteImport } from './routes/activar-ia'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as NewsletterSlugRouteImport } from './routes/newsletter.$slug'
import { Route as IndustriasTelecomunicacionesRouteImport } from './routes/industrias.telecomunicaciones'
import { Route as IndustriasSaludRouteImport } from './routes/industrias.salud'
import { Route as IndustriasRetailLogisticaRouteImport } from './routes/industrias.retail-logistica'
import { Route as IndustriasRealEstateRouteImport } from './routes/industrias.real-estate'
import { Route as IndustriasMineriaUtilitiesRouteImport } from './routes/industrias.mineria-utilities'
import { Route as IndustriasBancaFinanzasRouteImport } from './routes/industrias.banca-finanzas'
import { Route as IndustriasAutomotrizRouteImport } from './routes/industrias.automotriz'
import { Route as IndustriasAgroindustriaRouteImport } from './routes/industrias.agroindustria'

const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasRoute = IndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivarIaRoute = ActivarIaRouteImport.update({
  id: '/activar-ia',
  path: '/activar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsletterRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ServicesRoute,
} as any)
const NewsletterSlugRoute = NewsletterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsletterRoute,
} as any)
const IndustriasTelecomunicacionesRoute =
  IndustriasTelecomunicacionesRouteImport.update({
    id: '/telecomunicaciones',
    path: '/telecomunicaciones',
    getParentRoute: () => IndustriasRoute,
  } as any)
const IndustriasSaludRoute = IndustriasSaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => IndustriasRoute,
} as any)
const IndustriasRetailLogisticaRoute =
  IndustriasRetailLogisticaRouteImport.update({
    id: '/retail-logistica',
    path: '/retail-logistica',
    getParentRoute: () => IndustriasRoute,
  } as any)
const IndustriasRealEstateRoute = IndustriasRealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => IndustriasRoute,
} as any)
const IndustriasMineriaUtilitiesRoute =
  IndustriasMineriaUtilitiesRouteImport.update({
    id: '/mineria-utilities',
    path: '/mineria-utilities',
    getParentRoute: () => IndustriasRoute,
  } as any)
const IndustriasBancaFinanzasRoute = IndustriasBancaFinanzasRouteImport.update({
  id: '/banca-finanzas',
  path: '/banca-finanzas',
  getParentRoute: () => IndustriasRoute,
} as any)
const IndustriasAutomotrizRoute = IndustriasAutomotrizRouteImport.update({
  id: '/automotriz',
  path: '/automotriz',
  getParentRoute: () => IndustriasRoute,
} as any)
const IndustriasAgroindustriaRoute = IndustriasAgroindustriaRouteImport.update({
  id: '/agroindustria',
  path: '/agroindustria',
  getParentRoute: () => IndustriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activar-ia': typeof ActivarIaRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/industrias': typeof IndustriasRouteWithChildren
  '/newsletter': typeof NewsletterRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/talleres': typeof TalleresRoute
  '/industrias/agroindustria': typeof IndustriasAgroindustriaRoute
  '/industrias/automotriz': typeof IndustriasAutomotrizRoute
  '/industrias/banca-finanzas': typeof IndustriasBancaFinanzasRoute
  '/industrias/mineria-utilities': typeof IndustriasMineriaUtilitiesRoute
  '/industrias/real-estate': typeof IndustriasRealEstateRoute
  '/industrias/retail-logistica': typeof IndustriasRetailLogisticaRoute
  '/industrias/salud': typeof IndustriasSaludRoute
  '/industrias/telecomunicaciones': typeof IndustriasTelecomunicacionesRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activar-ia': typeof ActivarIaRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/industrias': typeof IndustriasRouteWithChildren
  '/talleres': typeof TalleresRoute
  '/industrias/agroindustria': typeof IndustriasAgroindustriaRoute
  '/industrias/automotriz': typeof IndustriasAutomotrizRoute
  '/industrias/banca-finanzas': typeof IndustriasBancaFinanzasRoute
  '/industrias/mineria-utilities': typeof IndustriasMineriaUtilitiesRoute
  '/industrias/real-estate': typeof IndustriasRealEstateRoute
  '/industrias/retail-logistica': typeof IndustriasRetailLogisticaRoute
  '/industrias/salud': typeof IndustriasSaludRoute
  '/industrias/telecomunicaciones': typeof IndustriasTelecomunicacionesRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/newsletter': typeof NewsletterIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activar-ia': typeof ActivarIaRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/industrias': typeof IndustriasRouteWithChildren
  '/newsletter': typeof NewsletterRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/talleres': typeof TalleresRoute
  '/industrias/agroindustria': typeof IndustriasAgroindustriaRoute
  '/industrias/automotriz': typeof IndustriasAutomotrizRoute
  '/industrias/banca-finanzas': typeof IndustriasBancaFinanzasRoute
  '/industrias/mineria-utilities': typeof IndustriasMineriaUtilitiesRoute
  '/industrias/real-estate': typeof IndustriasRealEstateRoute
  '/industrias/retail-logistica': typeof IndustriasRetailLogisticaRoute
  '/industrias/salud': typeof IndustriasSaludRoute
  '/industrias/telecomunicaciones': typeof IndustriasTelecomunicacionesRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activar-ia'
    | '/contact'
    | '/faqs'
    | '/industrias'
    | '/newsletter'
    | '/services'
    | '/talleres'
    | '/industrias/agroindustria'
    | '/industrias/automotriz'
    | '/industrias/banca-finanzas'
    | '/industrias/mineria-utilities'
    | '/industrias/real-estate'
    | '/industrias/retail-logistica'
    | '/industrias/salud'
    | '/industrias/telecomunicaciones'
    | '/newsletter/$slug'
    | '/services/$serviceSlug'
    | '/newsletter/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activar-ia'
    | '/contact'
    | '/faqs'
    | '/industrias'
    | '/talleres'
    | '/industrias/agroindustria'
    | '/industrias/automotriz'
    | '/industrias/banca-finanzas'
    | '/industrias/mineria-utilities'
    | '/industrias/real-estate'
    | '/industrias/retail-logistica'
    | '/industrias/salud'
    | '/industrias/telecomunicaciones'
    | '/newsletter/$slug'
    | '/services/$serviceSlug'
    | '/newsletter'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activar-ia'
    | '/contact'
    | '/faqs'
    | '/industrias'
    | '/newsletter'
    | '/services'
    | '/talleres'
    | '/industrias/agroindustria'
    | '/industrias/automotriz'
    | '/industrias/banca-finanzas'
    | '/industrias/mineria-utilities'
    | '/industrias/real-estate'
    | '/industrias/retail-logistica'
    | '/industrias/salud'
    | '/industrias/telecomunicaciones'
    | '/newsletter/$slug'
    | '/services/$serviceSlug'
    | '/newsletter/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivarIaRoute: typeof ActivarIaRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  IndustriasRoute: typeof IndustriasRouteWithChildren
  NewsletterRoute: typeof NewsletterRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  TalleresRoute: typeof TalleresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias': {
      id: '/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof IndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activar-ia': {
      id: '/activar-ia'
      path: '/activar-ia'
      fullPath: '/activar-ia'
      preLoaderRoute: typeof ActivarIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/newsletter/$slug': {
      id: '/newsletter/$slug'
      path: '/$slug'
      fullPath: '/newsletter/$slug'
      preLoaderRoute: typeof NewsletterSlugRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/industrias/telecomunicaciones': {
      id: '/industrias/telecomunicaciones'
      path: '/telecomunicaciones'
      fullPath: '/industrias/telecomunicaciones'
      preLoaderRoute: typeof IndustriasTelecomunicacionesRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/salud': {
      id: '/industrias/salud'
      path: '/salud'
      fullPath: '/industrias/salud'
      preLoaderRoute: typeof IndustriasSaludRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/retail-logistica': {
      id: '/industrias/retail-logistica'
      path: '/retail-logistica'
      fullPath: '/industrias/retail-logistica'
      preLoaderRoute: typeof IndustriasRetailLogisticaRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/real-estate': {
      id: '/industrias/real-estate'
      path: '/real-estate'
      fullPath: '/industrias/real-estate'
      preLoaderRoute: typeof IndustriasRealEstateRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/mineria-utilities': {
      id: '/industrias/mineria-utilities'
      path: '/mineria-utilities'
      fullPath: '/industrias/mineria-utilities'
      preLoaderRoute: typeof IndustriasMineriaUtilitiesRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/banca-finanzas': {
      id: '/industrias/banca-finanzas'
      path: '/banca-finanzas'
      fullPath: '/industrias/banca-finanzas'
      preLoaderRoute: typeof IndustriasBancaFinanzasRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/automotriz': {
      id: '/industrias/automotriz'
      path: '/automotriz'
      fullPath: '/industrias/automotriz'
      preLoaderRoute: typeof IndustriasAutomotrizRouteImport
      parentRoute: typeof IndustriasRoute
    }
    '/industrias/agroindustria': {
      id: '/industrias/agroindustria'
      path: '/agroindustria'
      fullPath: '/industrias/agroindustria'
      preLoaderRoute: typeof IndustriasAgroindustriaRouteImport
      parentRoute: typeof IndustriasRoute
    }
  }
}

interface IndustriasRouteChildren {
  IndustriasAgroindustriaRoute: typeof IndustriasAgroindustriaRoute
  IndustriasAutomotrizRoute: typeof IndustriasAutomotrizRoute
  IndustriasBancaFinanzasRoute: typeof IndustriasBancaFinanzasRoute
  IndustriasMineriaUtilitiesRoute: typeof IndustriasMineriaUtilitiesRoute
  IndustriasRealEstateRoute: typeof IndustriasRealEstateRoute
  IndustriasRetailLogisticaRoute: typeof IndustriasRetailLogisticaRoute
  IndustriasSaludRoute: typeof IndustriasSaludRoute
  IndustriasTelecomunicacionesRoute: typeof IndustriasTelecomunicacionesRoute
}

const IndustriasRouteChildren: IndustriasRouteChildren = {
  IndustriasAgroindustriaRoute: IndustriasAgroindustriaRoute,
  IndustriasAutomotrizRoute: IndustriasAutomotrizRoute,
  IndustriasBancaFinanzasRoute: IndustriasBancaFinanzasRoute,
  IndustriasMineriaUtilitiesRoute: IndustriasMineriaUtilitiesRoute,
  IndustriasRealEstateRoute: IndustriasRealEstateRoute,
  IndustriasRetailLogisticaRoute: IndustriasRetailLogisticaRoute,
  IndustriasSaludRoute: IndustriasSaludRoute,
  IndustriasTelecomunicacionesRoute: IndustriasTelecomunicacionesRoute,
}

const IndustriasRouteWithChildren = IndustriasRoute._addFileChildren(
  IndustriasRouteChildren,
)

interface NewsletterRouteChildren {
  NewsletterSlugRoute: typeof NewsletterSlugRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
}

const NewsletterRouteChildren: NewsletterRouteChildren = {
  NewsletterSlugRoute: NewsletterSlugRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
}

const NewsletterRouteWithChildren = NewsletterRoute._addFileChildren(
  NewsletterRouteChildren,
)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivarIaRoute: ActivarIaRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  IndustriasRoute: IndustriasRouteWithChildren,
  NewsletterRoute: NewsletterRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  TalleresRoute: TalleresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
